// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlmyoaqiiwpzhfvudkaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sbXlvYXFpaXdwemhmdnVka2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjE0MTEsImV4cCI6MjA2NDIzNzQxMX0.K-dLFJX4M89h5hEwi1s_X8C1VnvGsRWMOBDvZuRci2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);